ConnectionStrings:
  Default: server=192.168.50.178;database=eventbustest;user id=testuser;password=123123;
EventBus:
  RabbitMQ:
    Host: "192.168.50.178"
    UserName: rabbit
    Password: 8NnT2nUNoOwpBAue
