ConnectionStrings:
  Default: server=localhost;database=sqlservertest;user id=sa;password=Shashlik123123;Encrypt=True;TrustServerCertificate=True;
EventBus:
  RabbitMQ:
    Host: localhost
    UserName: rabbit
    Password: 123123
