ConnectionStrings:
  Default: server=localhost\SQLEXPRESS;database=eventbustest;user id=sa;password=Shashlik123123;
EventBus:
  RabbitMQ:
    Host: localhost
    UserName: rabbit
    Password: 123123
