ConnectionStrings:
  Default: server=192.168.50.178;database=kafkatest;user id=testuser;password=123123;
EventBus:
  Kafka:
    Properties:
      "bootstrap.servers": "192.168.50.178"
      "allow.auto.create.topics": "true"
