ConnectionStrings:
  Default: server=localhost;database=kafkatest;user id=root;password=123123;
EventBus:
  Kafka:
    Properties:
      "bootstrap.servers": "localhost"
      "allow.auto.create.topics": "true"
