ConnectionStrings:
  Default: server=localhost;database=kafktest;user id=root;password=123123;
EventBus:
  Kafka:
    Properties:
      - ["bootstrap.servers", "localhost:9092"]
      - ["allow.auto.create.topics", "true"]
