ConnectionStrings:
  Default: server=localhost;database=eventbustest;user id=root;password=123123;Pooling=True;Minimum Pool Size=5;Maximum Pool Size=10;  
EventBus:
  Kafka:
    Properties:
      "bootstrap.servers": "localhost"
      "allow.auto.create.topics": "true"