name: build and test

on:
  push:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.100

      - name: Setup MySql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql root password: '123123'
          mysql user: 'testuser'
          mysql password: '123123'

      - name: Setup PostgreSql
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '12.9'
          postgresql user: 'testuser'
          postgresql password: '123123'

      - name: Setup SqlServer
        uses: 280780363/sqlserver-action@v1.0
        with:
          accept eula: Y
          sa password: 'Shashlik123123'

      - name: Setup RabbitMQ
        uses: nijel/rabbitmq-action@v1.0.0

      - name: Setup Kafka
        uses: 280780363/kafka-action@v1.0
        with:
          kafka version: '2.8.1'
          zookeeper version: '3.8.1'

      - name: Setup MongoDb
        uses: 280780363/mongo-action@v1.0
        with:
          version: 6.0.2
          username: mongo
          password: 123123

      - name: Setup Pulsar
        uses: reugn/github-action-pulsar@v1
        with:
          version: 2.10.1

      - name: Setup Redis
        uses: getong/redis-action@v1
        with:
          redis password: '123123'
          redis version: 6.2.7

      - name: Install dependencies
        run: dotnet restore ./src/Shashlik.EventBus.sln
      - name: Test
        run: dotnet test ./src/Shashlik.EventBus.sln
      - name: Build
        run: dotnet build ./src/Shashlik.EventBus.sln --configuration Release --no-restore
      - name: Pack
        run: dotnet pack ./src/Shashlik.EventBus.sln --configuration Release --no-restore --output ./nugetPackages
      - name: Publish
        run: dotnet nuget push "./nugetPackages/*.nupkg" -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json