name: shashlik-nuget

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
      - name: Install dependencies
        run: dotnet restore ./src/Shashlik.EventBus.Packages.sln
      - name: Build
        run: dotnet build ./src/Shashlik.EventBus.Packages.sln --configuration Release --no-restore
      - name: Pack      
        run: dotnet pack ./src/Shashlik.EventBus.Packages.sln  -p:SymbolPackageFormat=snupkg --include-symbols  --include-source --configuration Release --no-restore --output ./nugetPackages
      - name: Publish
        run: dotnet nuget push "./nugetPackages/*.nupkg" -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json