name: Publish NuGet

on:
  push:
    tags:
      - "*"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 8.0.300

      - name: Install dotnet tool
        run: dotnet tool install -g dotnetCampus.TagToVersion

      - name: Set tag to version
        run: dotnet TagToVersion -t ${{ github.ref }} -f Directory.Build.props

      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish GameFrameX.EventBus
        uses: alianblank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: src/GameFrameX.EventBus/GameFrameX.EventBus.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.EventBus.Abstractions
        uses: alianblank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: src/GameFrameX.EventBus.Abstractions/GameFrameX.EventBus.Abstractions.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.EventBus.Dashboard
        uses: alianblank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: src/GameFrameX.EventBus.Dashboard/GameFrameX.EventBus.Dashboard.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: GameFrameX.EventBus.Extensions.EfCore
        uses: alianblank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: src/GameFrameX.EventBus.Extensions.EfCore/GameFrameX.EventBus.Extensions.EfCore.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.EventBus.RelationDbStorage
        uses: alianblank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: src/GameFrameX.EventBus.RelationDbStorage/GameFrameX.EventBus.RelationDbStorage.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.EventBus.Storage.Kafka
        uses: alianblank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: src/GameFrameX.EventBus.Storage.Kafka/GameFrameX.EventBus.Storage.Kafka.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.EventBus.Storage.MemoryQueue
        uses: alianblank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: src/GameFrameX.EventBus.Storage.MemoryQueue/GameFrameX.EventBus.Storage.MemoryQueue.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.EventBus.Storage.MemoryStorage
        uses: alianblank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: src/GameFrameX.EventBus.Storage.MemoryStorage/GameFrameX.EventBus.Storage.MemoryStorage.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.EventBus.Storage.MongoDb
        uses: alianblank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: src/GameFrameX.EventBus.Storage.MongoDb/GameFrameX.EventBus.Storage.MongoDb.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.EventBus.Storage.MySql
        uses: alianblank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: src/GameFrameX.EventBus.Storage.MySql/GameFrameX.EventBus.Storage.MySql.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.EventBus.Storage.PostgreSQL
        uses: alianblank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: src/GameFrameX.EventBus.Storage.PostgreSQL/GameFrameX.EventBus.Storage.PostgreSQL.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.EventBus.Storage.Pulsar
        uses: alianblank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: src/GameFrameX.EventBus.Storage.Pulsar/GameFrameX.EventBus.Storage.Pulsar.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.EventBus.Storage.RabbitMQ
        uses: alianblank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: src/GameFrameX.EventBus.Storage.RabbitMQ/GameFrameX.EventBus.Storage.RabbitMQ.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.EventBus.Storage.Redis
        uses: alianblank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: src/GameFrameX.EventBus.Storage.Redis/GameFrameX.EventBus.Storage.Redis.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.EventBus.Storage.Sqlite
        uses: alianblank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: src/GameFrameX.EventBus.Storage.Sqlite/GameFrameX.EventBus.Storage.Sqlite.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.EventBus.Dashboard
        uses: alianblank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: src/GameFrameX.EventBus.Dashboard/GameFrameX.EventBus.Dashboard.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish GameFrameX.EventBus.Storage.SqlServer
        uses: alianblank/publish-nuget@v1.0.2
        with:
          PROJECT_FILE_PATH: src/GameFrameX.EventBus.Storage.SqlServer/GameFrameX.EventBus.Storage.SqlServer.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
