name: Publish NuGet

on:
  #  push:
  #    branches: [ release ]
  push:
    tags:
      - "*"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 8.0.300

      - name: Install dependencies
        run: dotnet restore ./src/GameFrameX.EventBus.sln

      - name: Build
        run: dotnet build ./src/GameFrameX.EventBus.sln --configuration Release --no-restore

      - name: Pack
        run: dotnet pack ./src/GameFrameX.EventBus.sln --configuration Release --no-restore --output ./nugetPackages

      - name: Publish
        run: dotnet nuget push "./nugetPackages/*.nupkg" -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json