ConnectionStrings:
  Default: server=localhost;database=eventbustest;user id=root;password=123123;Pooling=True;Minimum Pool Size=5;Maximum Pool Size=10;
EventBus:
  RabbitMQ:
    Host: localhost
    UserName: rabbit
    Password: 123123
