ConnectionStrings:
  Default: server=192.168.50.178;database=eventbustest;user id=root;password=jizhen.cool.0416;Pooling=True;Min Pool Size=5;Max Pool Size=10;
EventBus:
  RabbitMQ:
    Host: "192.168.50.178"
    UserName: rabbit
    Password: 8NnT2nUNoOwpBAue
